### ISSUE TITLE
Docker implementation has hardcoded bremen_latest.pbf

### ISSUE THREAD

**Issue by michaelmgis** [michaelmgis/osmdata.xyz#11]
@riccardoklinger 
"bremen_latest.pbf" and download link are hardcoded in dockerfile and *.sh
Maybe consider it in readme.md for customization reasons.

**Comment by riccardoklinger** [comment]
we could think about two scenarioas: one test with a small array of tags for a small dataset like Bremen and the planet dump. so you could run it in "testmode" with hardcoded Bremen and a "productive" mode with planet dump...
