### ISSUE TITLE
Tents

### ISSUE THREAD

**Issue by brbrbr** [michaelmgis/osmdata.xyz#16]
Could you add the tents tag to the tourism database?

**Comment by michaelmgis** [comment]
maybe campsite is enough and can be found in "tourism".

**Comment by brbrbr** [comment]
Thanks for your response and the efforts to generate the data.

Tents is a yes/no flag used with caravan_site en camp_site to indicate
whether tents are allowed or not

regards

Bram

Op di 26 jan. 2021 20:10 schreef Michael <notifications@github.com>:

**Comment by michaelmgis** [comment]
My thoughts are: if adding tents, then the whole data model is affected by this information, which is not part of the primary map features. 

Maybe I could generate a special extract once? If you let me know what keys and tags are important to you, this shouldn't be a problem. hello@osmdata.xyz

**Comment by brbrbr** [comment]
Thanks for the offer, but I like to keep the data updates.

I use openstreetmap data to find campings and drinking water along planned
trips.


I though it would be as easy as adding a column to the tables like the
'fee' which is comparable to 'tents'.

the amount of results for ["tourism"="camp_site"]["tents"="no"] is small
enough to use overpass.
I use the results of overpass to refine your tables. The recent addition of
the osm_id field helped a lot to get that working

I had similar challenges with drinking water and the drinking_water yes/no
flag  (not the amenity=drinking_water) with fountains and springs.

the openstreetmap data is impressively inconsistent but a great source.

regards and thanks for your time.

Bram



Op di 26 jan. 2021 om 21:27 schreef Michael <notifications@github.com>:

**Comment by michaelmgis** [comment]
Hey Bram,
I'll add tents to the data model. If you really use this information, this shouldn't be a problem. The original objective was to add only the primary map features to the data model. The chances will be available  in the next month, during the next processing run.

My plan is to add a hstore_field with all remaining tags. 

Because I was curious, I extracted all information related to "tents": [https://download.osmdata.xyz/tents/tents_EPSG4326_20210118.zip](https://download.osmdata.xyz/tents/tents_EPSG4326_20210118.zip)

**Comment by michaelmgis** [comment]
Tents are now included in the updated files.

**Comment by brbrbr** [comment]
Hi Micheal,

thanks,

having the tents field saves me a lot of overpass-queries.

Just in case you are curious. I'm using the information to find campsites
and water point close to planned cycling tours.

A public playground is on https://gpx.logze.nl

It allows to add ypur own gpx track and then get all campsites and
drinkwater close to the track.

The campsites and bicycle shops are now extracted from your files. It's
crunching numbers right now, I try to find points, lines and polygon that
are actually  the same campsite.

For drinking water I still use the overpass. I would have to download three
of your files. amenity, natural and man_made. amenity I can handle the
other two are too big.


regards

bram


Op ma 8 feb. 2021 om 15:54 schreef Michael <notifications@github.com>:
