### ISSUE TITLE
Building and highway is missing

### ISSUE THREAD

**Issue by davidperrenoud** [michaelmgis/osmdata.xyz#17]
The following URLs currently return 404 Not Found:
http://download.osmdata.xyz/data/building_EPSG4326.zip
http://download.osmdata.xyz/data/highway_EPSG4326.zip

Thanks!

**Comment by michaelmgis** [comment]
Yes. There was a data loss issue :-| 
If you need the geometries, I can provide them from the last update. Otherwise, in two weeks, I'll start a regulary full update.

**Comment by michaelmgis** [comment]
I'll process the missing data right now. Should take two or three days

**Comment by davidperrenoud** [comment]
Thanks!

**Comment by michaelmgis** [comment]
Processing is done:
[http://download.osmdata.xyz/data/building_EPSG4326.zip](http://download.osmdata.xyz/data/building_EPSG4326.zip)

[http://download.osmdata.xyz/data/highway_EPSG4326.zip](http://download.osmdata.xyz/data/highway_EPSG4326.zip)
