### ISSUE TITLE
missing public tranpsort routes

### ISSUE THREAD

**Issue by riccardoklinger** [michaelmgis/osmdata.xyz#23]
When using the export from Oct/05 (public transport) I was expecting some bus routes of public transport for my city like this relation here:
<img width="1793" alt="grafik" src="https://user-images.githubusercontent.com/7377897/96547748-ede7d300-12ac-11eb-84ac-a0a0a8aab823.png">
Unfortunately the export just shows the "plattforms" of a stop. Is there a way to get all bus lines?

**Comment by michaelmgis** [comment]
At the moment, only geometries are extracted as points, lines and polygon. Bus routes are represented as [relation ](https://wiki.openstreetmap.org/wiki/Tag:route%3Dbus ) which leads to complex combinations of all types of geometries. 
The data model within a geopackage requires a distinction of geometries per feature class. 

Let's put this issue on a road map where special osm relations are stored as geopackage beside the global data sets. 

Thank you

**Comment by michaelmgis** [comment]
Update: Query geometries in relation is tricky in relatioal databases. 
I testet a on-premise overpass-api installation to query the bus routes. It works out for files smaller than 1,5 GB but not for larger extracts.

I continue checking.

**Comment by michaelmgis** [comment]
New workflow for this certain file: public_transport_with_relations: [https://github.com/michaelmgis/osmdata.xyz/blob/master/README.md#recent-improvements-and-changes](https://github.com/michaelmgis/osmdata.xyz/blob/master/README.md#recent-improvements-and-changes)
