### ISSUE TITLE
Are national parks included?

### ISSUE THREAD

**Issue by notflip** [michaelmgis/osmdata.xyz#24]
Thank you for maintaining this repo! I'm wondering if national parks are included?

**Comment by michaelmgis** [comment]
Hey, sorry for late reply. In OSM, national parks are mapped by a couple of tags: https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dnational_park

[boundary](https://download.osmdata.xyz/data/boundary_EPSG4326.zip)=national_park
[leisure](https://download.osmdata.xyz/data/leisure_EPSG4326.zip)=park 
[leisure](https://download.osmdata.xyz/data/leisure_EPSG4326.zip)=nature_reserve
