### ISSUE TITLE
Can't seem to unzip the downloaded packages

### ISSUE THREAD

**Issue by gjoliver** [michaelmgis/osmdata.xyz#33]
For example this small 7MB package.
https://download.osmdata.xyz/data/geological_EPSG4326.zip

Is there a special tool we need to use?
Thanks for all the work.

**Comment by michaelmgis** [comment]
The files seem to be broken. I'll fix that today.

**Comment by michaelmgis** [comment]
The data is in the processing pipeline right now with the latest planet file from August 16th. Website is updated. 
You can monitor the already available files here: [https://download.osmdata.xyz/data/](https://download.osmdata.xyz/data/)

Thank you for letting me know and opending the issue.
