### ISSUE TITLE
Excluding specifics from highway?

### ISSUE THREAD

**Issue by scfigg** [michaelmgis/osmdata.xyz#34]
This is exactly what I was looking for, for my laser cutting map project! However, there's a few things I can't have in my highways file - bike paths, construction, and parking aid/spaces. Is there a way for me to remove those in QGIS? Thanks! :)

**Comment by michaelmgis** [comment]
Hello! Great to hear that. 
If you like to exclude some features, "select by attribute" oder "select by expression" would be suitable. Afterwards, just delete the selected objects. 

Youtube Tutorial: [https://www.youtube.com/watch?v=nE7Y0HxMPVI](https://www.youtube.com/watch?v=nE7Y0HxMPVI)
