### ISSUE TITLE
https://download.osmdata.xyz/ is down

### ISSUE THREAD

**Issue by timini** [michaelmgis/osmdata.xyz#35]
Hi where can i download a full extract of OSM?

**Comment by michaelmgis** [comment]
Hey,
the website [https://download.osmdata.xyz/](https://download.osmdata.xyz/) is not down. There was maybe a connection issue on your side. Please check testing websites for your target servers like:

- [https://www.isitdownrightnow.com/download.osmdata.xyz.htm](https://www.isitdownrightnow.com/download.osmdata.xyz.htm)l
- [https://downforeveryoneorjustme.com/download.osmdata.xyz?proto=https](https://downforeveryoneorjustme.com/download.osmdata.xyz?proto=https)

**Comment by timini** [comment]
it must be my vpn blocking it, sorry for the issue
