### ISSUE TITLE
Unable to download Building File

### ISSUE THREAD

**Issue by niravgis** [michaelmgis/osmdata.xyz#37]
Unable to download building file. It shows No object found.

Please advise the alternate ways to download buildings for India.

**Comment by riccardoklinger** [comment]
confirmed! 
![grafik](https://user-images.githubusercontent.com/7377897/195303526-3fa60bbd-28c3-49c5-8bc1-8014d9a7a756.png)

**Comment by michaelmgis** [comment]
Buildings are ready to download.

**Comment by niravgis** [comment]
Hey Michael,

thank you for your quick response.

I am able to download but while unzipping, it shows "file is corrupted".

**Comment by michaelmgis** [comment]
I created an extract from buildings of India just for you: https://data.osmdata.xyz/india_building_EPSG4326.zip

In the meantime, I'll process the buildings again.

**Comment by michaelmgis** [comment]
Hello!
Reupload just finished. 
Please try https://data.osmdata.xyz/building_EPSG4326.zip

If you wish to load the GeoPackage directly, try: https://data.osmdata.xyz/building_EPSG4326.gpkg

Best regards

**Comment by niravgis** [comment]
Hi Michael

Thank you very much for your support.

Really appreciate your active participation.
