### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by michaelmgis** [michaelmgis/osmdata.xyz#6]
Add timestamp to attribute tables

**Comment by riccardoklinger** [comment]
would you like to have the timestamp from the processing timed inside the data or the timestamp of the pbf planet file?

**Comment by michaelmgis** [comment]
Timestamp of the objects in the pbf file. imposm does not provide it as output. Even osm2pgsql cannot do this. :-/

**Comment by riccardoklinger** [comment]
but you might be able to parse it from the pbf provider...

**Comment by michaelmgis** [comment]
This is an issue^^

**Comment by riccardoklinger** [comment]
okay, axel as the download machine creates its own timestamp. yet we could qget the md5 checksum file which then would still have a creation date according to the web resource. you can then use this with:
date -r planet-latest.osm.pbf.md5

**Comment by riccardoklinger** [comment]
the first steps of implementation is done here 
#12 
we still need an alter table statement to push this unix timestamp into the tables.

**Comment by michaelmgis** [comment]
No no. Not the unix timestamp. The OSM data model contains a time stamp for each geometry for when it was created/mapped. This was meant by timestamp.

**Comment by michaelmgis** [comment]
imposm makes it difficult and ogr2ogr has problems with large files. So this "issue" has no solution yet.
